name: QualityClouds

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Quality Clouds Scan
        uses: qualityclouds/action-full-scan@1.0.1
        with:
          mode: cloud
          token: ${{ secrets.QC_TOKEN }}
          url_id: ${{ secrets.QC_URL_ID }}
          version: latest
